
### Create shorten  url
POST https://98a64l2lp3.execute-api.ap-southeast-2.amazonaws.com/prod/shorten
Content-Type: application/json

{
  "originalUrl": "https://theprimeagen.github.io/fem-algos/lessons/our-first-algorithms/crystal-ball",
}


### Get url
GET https://98a64l2lp3.execute-api.ap-southeast-2.amazonaws.com/prod/2314bd7
